DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
    author_id INTEGER NOT NULL,
	author_name TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT UNIQUE NOT NULL,
	body TEXT NOT NULL,
	updated TIMESTAMP,
	body2 TEXT,
	body3 TEXT,
	body4 TEXT,
	body5 TEXT,
	body6 TEXT,
	body7 TEXT,
	FOREIGN KEY (author_id) REFERENCES user (id)
);